name: 部署文档

on:
  push:
    branches:
      - master

jobs:
  depoly-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Build Docs
        env:
          NODE-OPTIONS: --max_old_space_size=8192
        run: pnpm run docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: blog
          folder: docs/.vuepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}